@RedisExampleAPI_HostAddress = http://localhost:3001

GET {{RedisExampleAPI_HostAddress}}/jobs/2f4f49c8-0a0b-4374-8f24-39dab5f74e9e

###

POST {{RedisExampleAPI_HostAddress}}/jobs/submit
Content-Type: application/json
Accept: application/json

{
    "message": "Hello from AsyncEndpoints!",
    "delayInSeconds": 2
}

###

POST {{RedisExampleAPI_HostAddress}}/jobs/submit
Content-Type: application/json
Accept: application/json
Async-Job-Id: 442fab03-75db-4855-8ec7-b09e9538af02

{
    "message": "Hello from AsyncEndpoints!",
    "delayInSeconds": 2
}
