<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AsyncEndpoints.Core\AsyncEndpoints.Core.csproj" />
    <ProjectReference Include="..\AsyncEndpoints.Abstractions\AsyncEndpoints.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsAotCompatible>true</IsAotCompatible>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
