@AsyncEndpoints.API_HostAddress = http://localhost:5003

GET {{AsyncEndpoints.API_HostAddress}}/todos/
Accept: application/json

###

GET {{AsyncEndpoints.API_HostAddress}}/todos/1
Accept: application/json

###

POST {{AsyncEndpoints.API_HostAddress}}/todo-async
Accept: application/json
Content-Type: application/json
Async-Job-Id: 4f05bd49-224b-45ed-8d4f-47103c0c1291

{
    "id": 1,
    "title": "Ok"
}

###

POST {{AsyncEndpoints.API_HostAddress}}/todo-async
Accept: application/json
Content-Type: application/json

{
    "id": 1,
    "title": "Ok"
}