@AsyncEndpoints.API_HostAddress = http://localhost:5003

GET {{AsyncEndpoints.API_HostAddress}}/todos/
Accept: application/json

###

GET {{AsyncEndpoints.API_HostAddress}}/todos/1
Accept: application/json

###

POST {{AsyncEndpoints.API_HostAddress}}/todo-async
Accept: application/json
Content-Type: application/json
Async-Job-Id: 17fd1625-5d7b-4e18-a7c3-1921f9c8bfc9

{
    "id": 1,
    "title": "Ok"
}

###

POST {{AsyncEndpoints.API_HostAddress}}/todo-async
Accept: application/json
Content-Type: application/json

{
    "id": 1,
    "title": "Ok"
}