using System;

namespace AsyncEndpoints;

/// <summary>
/// Configuration settings for the AsyncEndpoints library.
/// </summary>
public sealed class AsyncEndpointsConfigurations
{
    /// <summary>
    /// Gets or sets the maximum number of retry attempts for failed jobs.
    /// Default value is 3.
    /// </summary>
    public int MaximumRetries { get; set; } = 3;

    /// <summary>
    /// Gets or sets the worker-specific configurations.
    /// </summary>
    public AsyncEndpointsWorkerConfigurations WorkerConfigurations { get; set; } = new();
}

/// <summary>
/// Configuration settings for AsyncEndpoints background workers.
/// </summary>
public sealed class AsyncEndpointsWorkerConfigurations
{
    /// <summary>
    /// Gets or sets the unique identifier for the worker instance.
    /// A new GUID is generated by default.
    /// </summary>
    public Guid WorkerId { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Gets or sets the maximum number of concurrent jobs the worker can process.
    /// Default value is the number of logical processors on the machine.
    /// </summary>
    public int MaximumConcurrency { get; set; } = Environment.ProcessorCount;

    /// <summary>
    /// Gets or sets the polling interval in milliseconds for checking new jobs.
    /// Default value is 1000ms (1 second).
    /// </summary>
    public int PollingIntervalMs { get; set; } = 1000;

    /// <summary>
    /// Gets or sets the timeout in minutes for job execution.
    /// Jobs that run longer than this will be marked as failed.
    /// Default value is 30 minutes.
    /// </summary>
    public int JobTimeoutMinutes { get; set; } = 30;

    /// <summary>
    /// Gets or sets the maximum number of jobs to process in a single batch.
    /// Default value is 5.
    /// </summary>
    public int BatchSize { get; set; } = 5;

    /// <summary>
    /// Gets or sets the maximum size of the job queue.
    /// Default value is 50 jobs.
    /// </summary>
    public int MaximumQueueSize { get; set; } = 50;
}
